### ISSUE TITLE
Get list of unique random integers

### ISSUE THREAD

**Issue by thijstriemstra** [RobTillaart/Prandom#3]
@RobTillaart how would I generate a list of unique random ints between X and Y?

**Comment by RobTillaart** [comment]
randrange(uint32_t start, uint32_t stop, uint32_t step) // step -s default 1

Prandom RR;
...
magic = RR.randrange(10, 42);

**Comment by thijstriemstra** [comment]
Maybe I should illustrate it better:

I have 5 audio tracks, and I want to playback them in random order. I need an array of 5 unique ints in random order, that I cycle through, so the track doesn't play twice.

So for example:

```
[4, 5, 3, 1, 2]
```

Your example could produce `[4, 4, 3, 1, 2]` no? There's no garantuee the list is unique.

In python I would use `random.shuffle` or `random.sample`: https://stackoverflow.com/questions/22842289/generate-n-unique-random-numbers-within-a-range but those methods don't seem to be implemented in this library.

**Comment by RobTillaart** [comment]
There are different strategies:

### not so clever method
keep track of your numbers you have drawn. redo if needed
has a fast start, but gets slower overtime. 
Works only with small sets.

### better method
randomize array with numbers you want. 
0. get a good random seed
1. create an array with all the numbers that can be selected   [1,2,3,4,5]
2. for (i = 0 to length array) swap(array i with a random one)
[1,2,3,4,5]  => [2,1,3,4,5] => [2,5,3,4,1] etc
3. repeat (2) as often as you prefer.
4. process the array from begin to end. 

drawback is most people need a lot of random calls because of step 3;

### best I know method
There is an optimized version that only needs N random calls for N nrs

```cpp

preparation

int ar[15];
// fill the array
for (int i = 0; i < 15; i++) ar[i] = i;     // fill it with your set.


int getRandomFromArray()
{
  static int n = 15;
  int idx = random(n);   // 0...14;
  int rv = ar[idx];
  n--;
  ar[idx] = ar[n];     // a non destructive version swaps these two elements..
  return rv;
}
```

**Comment by RobTillaart** [comment]
The trick is that as n gets smaller the set of numbers not chosen still is kept in 0..n

**Comment by thijstriemstra** [comment]
Thanks for the feedback. Unfortunately I do not know the size of the array until I loaded the tracks of the sdcard. It'll never be larger than 255 though. I was hoping there was a library, like yours, for this problem but seems I'm out of luck.. C++ is also not my daily programming language (thank god).

**Comment by thijstriemstra** [comment]
> Unfortunately I do not know the size of the array until I loaded the tracks of the sdcard. 

I seem to be able to dynamically declare an array like this:

```c++
int x, i;
int n = 15;
int *arr = new int(n);

// fill list
for (i = 0; i < n; i++) arr[i] = i;

// randomize list
for (i = 0; i < n; i++) {
  size_t j = random(i, n);

  // swap
  auto t = arr[i];
  arr[i] = arr[j];
  arr[j] = t;
}

// print list
for (x = 0; x < n; x++) {
  Serial.println(arr[x]);
}

// cleanup later
// delete [] arr;
```

prints:

```
3
11
5
2
1
7
4
14
12
13
6
10
9
0
8
```

**Comment by RobTillaart** [comment]
What platform do you use? 

C++ is just a language, and yes it has its drawbacks and its plusses like any language.

the trick above will work in (almost) any language as long as it supports array's  

#### Question 
How random should it be?

If you know the number of songs S you look for a number P that is prime with S. 
Then skip through the array in modulo steps.

#### Example
You have 120 songs S= 120 = (5,3,2 as dividers)
31 is prime with 120 . 
Then you play 
s0 = 31, s1 = 62, s3 = 93, s4 = 124 %120 = 4, s5 = 35, s6 = 66, s7 = 97, s8 = 128 %120 = 8 etc.

If you keep a list of the primes up to 255
2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163 ,167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251  (54 if I count correct, did I miss one?)
there will always be a prime that would do the job.   (and I think with some research you can cut that list in half or better)

**Comment by RobTillaart** [comment]
> > Unfortunately I do not know the size of the array until I loaded the tracks of the sdcard.
> 
> I seem to be able to dynamically declare an array like this:
> 
> ...

Looks random enough to me!

**Comment by RobTillaart** [comment]
If you can make a complete sketch of your code I will add it to the examples

**Comment by thijstriemstra** [comment]
> What platform do you use?

```
[env:hold-the-line]
platform = espressif8266
board = d1_mini
framework = arduino
```

> How random should it be?

It can be a list that is defined once at startup of the device.

> Looks random enough to me!

Agreed.

> If you can make a complete sketch of your code I will add it to the examples

It's not using this library though (should it?).

**Comment by RobTillaart** [comment]
> It's not using this library though (should it?).
that's a good point, just skip that remark :)

**Comment by thijstriemstra** [comment]
Unfortunately my solution doesn't seem to work with bigger loops somehow. Changing `n` to 150 results in a crash.. ugh

```
--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Exception (28):
epc1=0x4020609b epc2=0x00000000 epc3=0x00000000 excvaddr=0x0000008a depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffdc0 end: 3fffffc0 offset: 0190
3fffff50:  3fffdad0 00000001 3ffefb3c 402060dc  
3fffff60:  0000169b 00000000 3ffefb24 402060f4  
3fffff70:  00000000 3fff0168 3fff0154 402017c9  
3fffff80:  3fffdad0 00000000 3ffefa64 40201f9b  
3fffff90:  3fffdad0 00000000 3ffeec38 4020444b  
3fffffa0:  feefeffe feefeffe 3ffeec38 402094d0  
3fffffb0:  feefeffe feefeffe 3ffe84ec 40101389  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------
```

**Comment by RobTillaart** [comment]
A 8266 should have enough memory to have an array of 255 bytes. One can use 32 bytes to indicate a song.
back in 30 minutes.

**Comment by thijstriemstra** [comment]
I'm now using your Set library for a different approach.

**Comment by RobTillaart** [comment]
Give this a try
```cpp
//
//    FILE: SET_random_playlist.ino
//  AUTHOR: Rob Tillaart
// VERSION: 0.1.0
// PURPOSE: demo playlist with set
//    DATE: 2021-05-04
//     URL: https://github.com/RobTillaart/SET

#include "set.h"


Set playList;

int SONGS = 15;

uint32_t start, stop ;

void setup()
{
  Serial.begin(115200);
  Serial.println(__FILE__);
}


void loop()
{
  start = micros();
  for (int i = 0; i < SONGS; i++)
  {
    int s = getRandomSong();
    Serial.print(i);
    Serial.print('\t');
    Serial.println(s);
  }
  stop = micros();
  Serial.print("TIME: ");
  Serial.println(stop - start);
  delay(1000);
}


int getRandomSong()
{
  if (playList.isEmpty())
  {
    Serial.println("FILL THE ARRAY");
    for (int i = 0; i < SONGS; i++)
    {
      playList.add(i);
    }
  }
  int rv = random(SONGS);
  if (playList.has(rv) == false)
  {
    for (int i = rv; i < rv + SONGS; i++)
    {
      int idx = i % SONGS;
      if (playList.has(idx))
      {
        rv = idx;
        break;
      }
    }
  }
  playList.sub(rv);
  return rv;
}

// -- END OF FILE --
```

**Comment by RobTillaart** [comment]
It is definitely not mathematically perfect random, but it is pretty fast.

**Comment by thijstriemstra** [comment]
got caught up in a phonecall but your code looks like what I was going tot try as well, with `has()` etc. I'll give it a try!

**Comment by RobTillaart** [comment]
Added it to the SET library

**Comment by thijstriemstra** [comment]
Tested this in a for loop and no crashes, so I think I'm good to go. Thanks for your help.

```c++
int SONGS = 347;
for (int i = 0; i < SONGS; i++) {
    int rv = getRandomTrack();
    Serial.print("Sub: ");
    Serial.println(rv);
  }
```

I didn't expect to see "FILL THE ARRAY" printed twice with the previous for loop but it'll make sense later I guess 😃 

```
FILL THE ARRAY
Sub: 107
Sub: 137
Sub: 154
Sub: 42
Sub: 102
Sub: 23
Sub: 290
Sub: 185
Sub: 342
Sub: 43
Sub: 3
Sub: 116
Sub: 8
Sub: 283
Sub: 343
Sub: 314
Sub: 253
Sub: 164
Sub: 215
Sub: 321
Sub: 145
Sub: 285
Sub: 35
Sub: 242
Sub: 24
Sub: 330
Sub: 96
Sub: 220
Sub: 75
Sub: 266
Sub: 11
Sub: 105
Sub: 81
Sub: 80
Sub: 128
Sub: 268
Sub: 277
Sub: 273
Sub: 131
Sub: 169
Sub: 45
Sub: 229
Sub: 70
Sub: 38
Sub: 256
Sub: 1
Sub: 133
Sub: 246
Sub: 303
Sub: 158
Sub: 302
Sub: 213
Sub: 73
Sub: 191
Sub: 216
Sub: 69
Sub: 103
Sub: 117
Sub: 312
Sub: 338
Sub: 304
Sub: 104
Sub: 305
Sub: 328
Sub: 68
Sub: 77
Sub: 306
Sub: 240
Sub: 228
Sub: 19
Sub: 286
Sub: 260
Sub: 284
Sub: 153
Sub: 89
Sub: 36
Sub: 175
Sub: 148
Sub: 114
Sub: 346
Sub: 196
Sub: 307
Sub: 13
Sub: 59
Sub: 121
Sub: 97
Sub: 159
Sub: 276
Sub: 2
Sub: 186
Sub: 63
Sub: 5
Sub: 222
Sub: 171
Sub: 79
Sub: 40
Sub: 182
Sub: 84
Sub: 339
Sub: 188
Sub: 22
Sub: 287
Sub: 200
Sub: 71
Sub: 25
Sub: 230
Sub: 26
Sub: 243
Sub: 217
Sub: 207
Sub: 334
Sub: 214
Sub: 254
Sub: 157
Sub: 44
Sub: 270
Sub: 52
Sub: 332
Sub: 32
Sub: 289
Sub: 85
Sub: 94
Sub: 161
Sub: 218
Sub: 262
Sub: 181
Sub: 293
Sub: 53
Sub: 197
Sub: 15
Sub: 295
Sub: 313
Sub: 219
Sub: 54
Sub: 88
Sub: 7
Sub: 41
Sub: 183
Sub: 98
Sub: 187
Sub: 55
Sub: 60
Sub: 241
Sub: 227
Sub: 177
Sub: 118
Sub: 16
Sub: 199
Sub: 317
Sub: 122
Sub: 250
Sub: 203
Sub: 231
Sub: 255
Sub: 91
Sub: 99
Sub: 149
Sub: 9
Sub: 204
Sub: 232
Sub: 237
Sub: 318
Sub: 205
Sub: 274
Sub: 211
Sub: 147
Sub: 184
Sub: 223
Sub: 320
Sub: 66
Sub: 132
Sub: 106
Sub: 224
Sub: 144
Sub: 179
Sub: 245
Sub: 67
Sub: 221
Sub: 92
Sub: 93
Sub: 95
Sub: 100
Sub: 101
Sub: 225
Sub: 108
Sub: 109
Sub: 110
Sub: 111
Sub: 134
Sub: 112
Sub: 113
Sub: 115
Sub: 119
Sub: 120
Sub: 123
Sub: 124
Sub: 125
Sub: 126
Sub: 127
Sub: 129
Sub: 130
Sub: 206
Sub: 135
Sub: 136
Sub: 138
Sub: 139
Sub: 140
Sub: 141
Sub: 233
Sub: 234
Sub: 142
Sub: 143
Sub: 146
Sub: 150
Sub: 151
Sub: 247
Sub: 152
Sub: 178
Sub: 155
Sub: 156
Sub: 160
Sub: 162
Sub: 208
Sub: 163
Sub: 165
Sub: 166
Sub: 167
Sub: 168
Sub: 226
Sub: 170
Sub: 172
Sub: 173
Sub: 174
Sub: 176
Sub: 180
Sub: 189
Sub: 190
Sub: 192
Sub: 235
Sub: 193
Sub: 194
Sub: 209
Sub: 195
Sub: 236
Sub: 198
Sub: 201
Sub: 202
Sub: 210
Sub: 212
Sub: 238
Sub: 239
Sub: 244
Sub: 248
Sub: 249
Sub: 251
Sub: 252
FILL THE ARRAY
Sub: 187
Sub: 163
Sub: 324
Sub: 257
Sub: 162
Sub: 133
Sub: 247
Sub: 28
Sub: 281
Sub: 224
Sub: 154
Sub: 199
Sub: 230
Sub: 338
Sub: 298
Sub: 240
Sub: 335
Sub: 134
Sub: 147
Sub: 23
Sub: 170
Sub: 36
Sub: 171
Sub: 223
Sub: 238
Sub: 290
Sub: 197
Sub: 295
Sub: 299
Sub: 239
Sub: 258
Sub: 307
Sub: 20
Sub: 237
Sub: 35
Sub: 241
Sub: 152
Sub: 157
Sub: 11
Sub: 215
Sub: 300
Sub: 306
Sub: 4
Sub: 69
Sub: 24
Sub: 62
Sub: 86
Sub: 246
Sub: 212
Sub: 88
Sub: 184
Sub: 308
Sub: 312
Sub: 211
Sub: 263
Sub: 243
Sub: 189
Sub: 45
Sub: 252
Sub: 221
Sub: 341
Sub: 227
Sub: 84
Sub: 136
Sub: 216
Sub: 228
Sub: 96
Sub: 316
Sub: 17
Sub: 15
Sub: 278
Sub: 206
Sub: 70
Sub: 293
Sub: 210
Sub: 103
Sub: 207
Sub: 198
Sub: 61
Sub: 248
Sub: 126
Sub: 194
Sub: 108
Sub: 222
Sub: 139
Sub: 87
Sub: 262
Sub: 213
Sub: 46
Sub: 180
Sub: 27
```

**Comment by RobTillaart** [comment]
The set can hold at most 255 elements, I think that is the cause of the problem.

If you need more unique numbers, have a look at bitArray library which can hold up to 65535 elements ...

**Comment by thijstriemstra** [comment]
> The set can hold at most 255 elements, I think that is the cause of the problem.

Gotcha! I think I also looked at bitArray but couldn't find a `has` method. I shouldn't have tested it with more than 255, because 255 is the max tracks I can use, so no worries!

**Comment by RobTillaart** [comment]
bitArray has a **get(index)** function, so the **has(index)** is very easy to code.
Also a **set(index, value)** is available ...

**Comment by thijstriemstra** [comment]
I can switch but "don't change if it's not broken" will do for now. ;)
